# 00 · Download the raw data

**Goal:** get every source we chose in the data research onto this computer, exactly as published, before we clean or model anything.

**Scope:** New York City first, government sources, at least 5 years of history.

**What this notebook does:**
1. Reads the list of sources from `src/sources.py`. That is the only place URLs and versions live.
2. Downloads each one into `data/raw/<group>/<source>/`. Files already on disk are skipped, so it is safe to rerun.
3. Logs every file in `data/raw/manifest.csv`: URL, download time, size and SHA-256 fingerprint. That lets us prove later which file produced which number.
4. Dates the file name for snapshot sources, the ones whose publisher overwrites them (NYC Jobs, the NYS DOL wage table, and others). Each rerun keeps a new copy, so we build our own history.

**What it does not do:** clean, filter or reshape anything. That happens one source at a time in the next notebooks.

Background for every source: `docs/plans/data-research/README.md` and reports `00`–`06`.

In [1]:
import sys
from datetime import date
from pathlib import Path

import pandas as pd
import requests

sys.path.insert(0, str(Path.cwd().parent / "src"))
from common import RAW
import sources as S

TODAY = date.today().isoformat()
REGISTRY = S.build_registry()
session = requests.Session()
print(f"{len(REGISTRY)} files in the registry, saving under {RAW}")

155 files in the registry, saving under <repo>\data\raw

## The list of sources
One row per file. `snapshot` = the publisher overwrites it, so we keep dated copies.

In [2]:
reg = pd.DataFrame(REGISTRY)
reg["snapshot"] = reg.get("snapshot", False).fillna(False).astype(bool)
reg.groupby(["group", "key"]).agg(files=("file", "count"), snapshot=("snapshot", "max"),
                                  note=("note", "first")).reset_index()

,group,key,files,snapshot,note
0,bls_timeseries,bls_cu,7,True,CPI-U all items by area (NY-Newark-Jersey City...
1,bls_timeseries,bls_jt,11,True,"JOLTS openings/hires/quits/layoffs, US + state..."
2,bls_timeseries,bls_la,7,True,"LAUS unemployment, NY areas incl. the 5 boroug..."
3,graduates,cuny_degrees_by_type,1,False,CUNY degrees granted by type (tie-out)
4,graduates,cuny_enrollment,1,False,CUNY enrollment trends by college
5,graduates,cuny_programs,1,False,"CUNY graduates and fall enrollment by program,..."
6,graduates,ipeds_completions,10,False,"Completions by college x CIP x award, academic..."
7,graduates,ipeds_dictionary,1,False,NaN
8,graduates,ipeds_directory,10,False,Institution directory
9,graduates,nces_cip,3,False,CIP 2010 -> 2020 (IPEDS before C2020 uses CIP ...
10,hiring,census_qwi,4,False,"QWI hires/separations, county x NAICS sector x..."
11,hiring,nysdol_ui_beneficiaries,1,False,"UI beneficiaries by county, monthly since 2001"
12,jobs,bea_county_gdp,2,True,"GDP by county x industry, current dollars (NYC..."
13,jobs,bls_ep_education,1,True,"Entry education, experience, training; attainm..."
14,jobs,bls_ind_occ_matrix,1,True,National employment matrix: jobs within each i...
15,jobs,bls_oews_metro,8,False,"OEWS May 2018, all metro areas (NY = 35620)"
16,jobs,bls_oews_research,6,False,OEWS research estimates May 2019: state x indu...
17,jobs,bls_soc_crosswalk,1,False,Needed for OEWS 2018-2020 and older projections
18,jobs,nysdol_ces,1,False,CES monthly jobs by industry since 1990 (NYC a...
19,jobs,nysdol_oews_regions,1,True,"NYS DOL wages by region incl. NYC 5 boroughs, ..."
20,jobs,nysdol_projections,1,True,"Long-term projections, current vintage (NYC 20..."
21,jobs,nysdol_projections_archive,3,False,"NYC 2016-2026 vintage, Wayback capture 2021032..."
22,jobs,nysdol_qcew_annual,1,False,"QCEW annual jobs/wages by county x NAICS, 2000..."
23,licensing,nys_license_soc,1,False,"NY license -> SOC crosswalk (has known errors,..."
24,licensing,nysed_license_stats_index,1,True,Index page; links to per-profession stats
25,licensing,nysed_nclex,8,False,RN NCLEX first-time pass rates by school
26,licensing,nysed_registrants,29,False,"Registered licensees per profession, April 1"
27,outcomes,acs_pums,5,False,ACS PUMS NY persons 2020-2024 (major x job x a...
28,outcomes,census_pseo,2,False,Earnings by college x major
29,outcomes,nyfed_recent_grads,2,True,Unemployment/underemployment/wages by major (US)
30,outcomes,scorecard_fos,1,False,College Scorecard field of study
31,pay,dol_oflc_wages,6,False,"Prevailing wage Levels I-IV by SOC x area, Jul..."
32,pay,nyc_payroll,7,False,NYC payroll FY2019; employee names deliberatel...
33,postings,indeed_hiring_lab,4,True,"Indeed Hiring Lab postings index (CC BY 4.0), ..."
34,postings,nyc_civil_titles,1,True,DCAS civil service title codes
35,postings,nyc_jobs,1,True,"NYC government postings; no history kept, so s..."
36,skills,onet,4,False,O*NET 31.0 (Aug 2026)

## Download, group by group

Each group below is one part of the question chain:

| Group | Answers |
|---|---|
| `jobs` | How many people work in each job, pay, projected openings (2018–2025 and 4 projection editions); NYC economic output (GDP) by industry; which jobs each industry hires (NY State 2019–2024, US matrix) |
| `hiring` | Hires and separations by age group in the 5 boroughs; unemployment benefits |
| `licensing` | Licensed people per profession 1997–2025; nursing exam pass rates by school |
| `graduates` | CUNY and other NYC college graduates by major, 2015–2025; CUNY enrollment by program |
| `outcomes` | What graduates earn and do (PSEO, Scorecard, Census microdata, NY Fed) |
| `pay` | Entry-level wage levels by year; NYC government pay by year |
| `bls_timeseries` | NY metro prices (CPI), NY State openings/hires/layoffs (JOLTS), borough unemployment (LAUS) |
| `skills` / `postings` | Skills per job (O\*NET); current NYC government postings; Indeed postings index |

The biggest files are the Census microdata (~140 MB), the Census hiring files (~160 MB each) and the NYS DOL industry table. The first run takes a while.

In [3]:
def run_group(group):
    rows = [S.fetch(src, TODAY, session) for src in REGISTRY if src["group"] == group]
    out = pd.DataFrame(rows)
    out["MB"] = (out["bytes"] / 1e6).round(1)
    return out.drop(columns="bytes")

log = {}

### `jobs`

In [4]:
log["jobs"] = run_group("jobs")
log["jobs"]

                                                 file        status     MB
0                    jobs/bls_oews_metro/oesm18ma.zip  already have   31.2
1                    jobs/bls_oews_metro/oesm19ma.zip  already have   35.5
2                    jobs/bls_oews_metro/oesm20ma.zip  already have   36.4
3                    jobs/bls_oews_metro/oesm21ma.zip  already have   38.9
4                    jobs/bls_oews_metro/oesm22ma.zip  already have   39.0
5                    jobs/bls_oews_metro/oesm23ma.zip  already have   39.2
6                    jobs/bls_oews_metro/oesm24ma.zip  already have   40.2
7                    jobs/bls_oews_metro/oesm25ma.zip  already have   39.9
8   jobs/nysdol_oews_regions/gkgz-nw24_2026-10-12.csv  already have    0.7
9    jobs/nysdol_projections/pqm4-9qqb_2026-10-12.csv  already have    0.7
10  jobs/nysdol_projections_archive/pqm4-9qqb_2016...  already have    0.7
11  jobs/nysdol_projections_archive/pqm4-9qqb_2018...  already have    0.7
12  jobs/nysdol_projections_archive/pqm4-9qqb_2020...  already have    0.6
13              jobs/nysdol_qcew_annual/shc7-xcbw.csv  already have  128.0
14                      jobs/nysdol_ces/6k74-dgkb.csv  already have   37.1
15  jobs/bls_soc_crosswalk/soc_2010_to_2018_crossw...  already have    0.0
16    jobs/bls_ep_education/education_2026-10-12.xlsx  already have    0.1
17          jobs/bea_county_gdp/CAGDP2_2026-10-12.zip    downloaded   15.3
18          jobs/bea_county_gdp/CAGDP9_2026-10-12.zip    downloaded   15.4
19     jobs/bls_ind_occ_matrix/matrix_2026-10-12.xlsx    downloaded    7.9
20  jobs/bls_oews_research/oes_research_2019_allse...    downloaded  132.6
21  jobs/bls_oews_research/oes_research_2020_allse...    downloaded  136.9
22  jobs/bls_oews_research/oes_research_2021_allse...    downloaded  135.7
23  jobs/bls_oews_research/oes_research_2022_allse...    downloaded  139.4
24  jobs/bls_oews_research/oes_research_2023_allse...    downloaded  146.1
25  jobs/bls_oews_research/oes_research_2024_allse...    downloaded  155.1

### `hiring`

In [5]:
log["hiring"] = run_group("hiring")
log["hiring"]

                                              file        status     MB
0  hiring/census_qwi/qwi_ny_sa_f_gc_ns_op_u.csv.gz  already have  167.2
1  hiring/census_qwi/qwi_ny_se_f_gc_ns_op_u.csv.gz  already have  120.7
2                  hiring/census_qwi/qwi_ny.md5sum  already have    0.0
3                hiring/census_qwi/version_qwi.txt  already have    0.0
4     hiring/nysdol_ui_beneficiaries/xbjp-8sra.csv  already have    0.8

### `licensing`

In [6]:
log["licensing"] = run_group("licensing")
log["licensing"]

                                                 file        status   MB
0   licensing/nysed_registrants/numbers-registered...  already have  0.0
1   licensing/nysed_registrants/numbers-registered...  already have  0.0
2   licensing/nysed_registrants/numbers-registered...  already have  0.0
3   licensing/nysed_registrants/numbers-registered...  already have  0.0
4   licensing/nysed_registrants/numbers-registered...  already have  0.0
5   licensing/nysed_registrants/numbers-registered...  already have  0.0
6   licensing/nysed_registrants/numbers-registered...  already have  0.0
7   licensing/nysed_registrants/numbers-registered...  already have  0.0
8   licensing/nysed_registrants/numbers-registered...  already have  0.0
9   licensing/nysed_registrants/numbers-registered...  already have  0.0
10  licensing/nysed_registrants/numbers-registered...  already have  0.0
11  licensing/nysed_registrants/numbers-registered...  already have  0.0
12  licensing/nysed_registrants/numbers-registered...  already have  0.0
13  licensing/nysed_registrants/numbers-registered...  already have  0.0
14  licensing/nysed_registrants/numbers-registered...  already have  0.0
15  licensing/nysed_registrants/numbers-registered...  already have  0.0
16  licensing/nysed_registrants/numbers-registered...  already have  0.0
17  licensing/nysed_registrants/numbers-registered...  already have  0.0
18  licensing/nysed_registrants/numbers-registered...  already have  0.0
19  licensing/nysed_registrants/numbers-registered...  already have  0.0
20  licensing/nysed_registrants/numbers-registered...  already have  0.0
21  licensing/nysed_registrants/numbers-registered...  already have  0.0
22  licensing/nysed_registrants/numbers-registered...  already have  0.0
23  licensing/nysed_registrants/numbers-registered...  already have  0.0
24  licensing/nysed_registrants/numbers-registered...  already have  0.0
25  licensing/nysed_registrants/numbers-registered...  already have  0.0
26  licensing/nysed_registrants/numbers-registered...  already have  0.0
27  licensing/nysed_registrants/numbers-registered...  already have  0.0
28  licensing/nysed_registrants/numbers-registered...  already have  0.0
29  licensing/nysed_license_stats_index/registrati...  already have  0.0
30      licensing/nysed_nclex/nclex-rn-2008-2012.html  already have  0.1
31      licensing/nysed_nclex/nclex-rn-2013-2017.html  already have  0.1
32      licensing/nysed_nclex/nclex-rn-2018-2022.html  already have  0.1
33      licensing/nysed_nclex/nclex-rn-2023-2027.html  already have  0.1
34      licensing/nysed_nclex/nclex-pn-2008-2012.html  already have  0.1
35      licensing/nysed_nclex/nclex-pn-2013-2017.html  already have  0.1
36      licensing/nysed_nclex/nclex-pn-2018-2022.html  already have  0.1
37      licensing/nysed_nclex/nclex-pn-2023-2027.html  already have  0.1
38            licensing/nys_license_soc/w2w4-tdxt.csv  already have  0.0

### `graduates`

In [7]:
log["graduates"] = run_group("graduates")
log["graduates"]

                                                 file        status    MB
0             graduates/ipeds_completions/C2015_A.zip  already have   8.9
1                graduates/ipeds_directory/HD2015.zip  already have   1.1
2             graduates/ipeds_completions/C2016_A.zip  already have   8.9
3                graduates/ipeds_directory/HD2016.zip  already have   1.2
4             graduates/ipeds_completions/C2017_A.zip  already have   8.9
5                graduates/ipeds_directory/HD2017.zip  already have   1.1
6             graduates/ipeds_completions/C2018_A.zip  already have   8.5
7                graduates/ipeds_directory/HD2018.zip  already have   1.1
8             graduates/ipeds_completions/C2019_A.zip  already have   8.5
9                graduates/ipeds_directory/HD2019.zip  already have   1.0
10            graduates/ipeds_completions/C2020_A.zip  already have   8.5
11               graduates/ipeds_directory/HD2020.zip  already have   1.0
12            graduates/ipeds_completions/C2021_A.zip  already have   8.4
13               graduates/ipeds_directory/HD2021.zip  already have   1.0
14            graduates/ipeds_completions/C2022_A.zip  already have   8.3
15               graduates/ipeds_directory/HD2022.zip  already have   1.1
16            graduates/ipeds_completions/C2023_A.zip  already have   9.3
17               graduates/ipeds_directory/HD2023.zip  already have   1.1
18            graduates/ipeds_completions/C2024_A.zip  already have   4.7
19               graduates/ipeds_directory/HD2024.zip  already have   1.1
20        graduates/ipeds_dictionary/C2024_A_Dict.zip  already have   0.1
21         graduates/nces_cip/Crosswalk2010to2020.csv  already have   0.3
22                 graduates/nces_cip/CIPCode2020.csv  already have   1.1
23  graduates/nces_cip/CIP2020_SOC2018_Crosswalk.xlsx  already have   0.4
24              graduates/cuny_programs/28gk-bu58.csv  already have  16.7
25       graduates/cuny_degrees_by_type/ybg5-afvs.csv  already have   0.0
26            graduates/cuny_enrollment/487n-fp4r.csv  already have   0.2

### `outcomes`

In [8]:
log["outcomes"] = run_group("outcomes")
log["outcomes"]

                                                file        status     MB
0               outcomes/census_pseo/pseoe_ny.csv.gz  already have    0.9
1               outcomes/census_pseo/pseof_ny.csv.gz  already have   12.3
2  outcomes/scorecard_fos/Most-Recent-Cohorts-Fie...  already have   17.2
3        outcomes/acs_pums/csv_pny_2020-2024_5yr.zip  already have  140.1
4  outcomes/acs_pums/PUMS_Data_Dictionary_2020-20...  already have    0.3
5         outcomes/acs_pums/2024_ACS_Code_Lists.xlsx  already have    0.3
6  outcomes/acs_pums/2018-occupation-code-list-an...  already have    0.2
7  outcomes/acs_pums/2020_Census_Tract_to_2020_PU...  already have    1.7
8  outcomes/nyfed_recent_grads/college-labor-outc...  already have    0.0
9  outcomes/nyfed_recent_grads/College-labor-data...  already have    0.1

### `pay`

In [9]:
log["pay"] = run_group("pay")
log["pay"]

                                            file        status    MB
0      pay/dol_oflc_wages/OFLC_Wages_2021-22.zip  already have  12.2
1      pay/dol_oflc_wages/OFLC_Wages_2022-23.zip  already have  13.5
2      pay/dol_oflc_wages/OFLC_Wages_2023-24.zip  already have  13.7
3      pay/dol_oflc_wages/OFLC_Wages_2024-25.zip  already have  12.4
4      pay/dol_oflc_wages/OFLC_Wages_2025-26.zip  already have  12.3
5      pay/dol_oflc_wages/OFLC_Wages_2026-27.zip  already have  12.7
6   pay/nyc_payroll/k397-673e_fy2019_nonames.csv  already have  83.2
7   pay/nyc_payroll/k397-673e_fy2020_nonames.csv  already have  82.5
8   pay/nyc_payroll/k397-673e_fy2021_nonames.csv  already have  80.0
9   pay/nyc_payroll/k397-673e_fy2022_nonames.csv  already have  85.7
10  pay/nyc_payroll/k397-673e_fy2023_nonames.csv  already have  77.5
11  pay/nyc_payroll/k397-673e_fy2024_nonames.csv  already have  78.9
12  pay/nyc_payroll/k397-673e_fy2025_nonames.csv  already have  77.3

### `skills`

In [10]:
log["skills"] = run_group("skills")
log["skills"]

                                         file        status    MB
0                 skills/onet/db_31_0_csv.zip  already have  16.2
1                skills/onet/db_30_0_text.zip  already have  13.5
2      skills/onet/2019_to_SOC_Crosswalk.xlsx  already have   0.4
3  skills/onet/Education_CIP_to_ONET_SOC.xlsx  already have   0.2

### `postings`

In [11]:
log["postings"] = run_group("postings")
log["postings"]

                                                file        status    MB
0         postings/nyc_jobs/kpav-sd4t_2026-10-12.csv  already have  18.1
1  postings/nyc_civil_titles/nzjr-3966_2026-10-12...  already have   0.4
2  postings/indeed_hiring_lab/aggregate_job_posti...  already have   0.2
3  postings/indeed_hiring_lab/state_job_postings_...  already have   2.6
4  postings/indeed_hiring_lab/metro_job_postings_...  already have  62.6
5  postings/indeed_hiring_lab/job_postings_by_sec...  already have  12.1

### `bls_timeseries` (BLS monthly series, bulk files)

Three monthly series from the BLS bulk-file server (`download.bls.gov/pub/time.series/`):
- CPI-U for the NY metro area (`cu`, area S12A). Used to show pay over time in today's dollars.
- **JOLTS for New York State** (`jt`, state 36). Job openings, hires, quits and layoffs. Industry detail is only published for the whole US.
- Unemployment rate (LAUS) for each of the 5 borough counties (`la`).

Why bulk files, not the API: the first run used the free BLS API, which without a key allows only a few requests per day per internet address (IP). Earlier research had used up the day's allowance, so all 3 pulls came back `REQUEST_NOT_PROCESSED`. The bulk files hold the full history (JOLTS from 2000, LAUS from 1976) with no daily cap, and they are the same numbers. BLS revises them in place, so they are dated snapshots. The series IDs we will read out of them are in `S.BLS_SERIES`.

In [12]:
log["bls_timeseries"] = run_group("bls_timeseries")
log["bls_timeseries"]

                                                 file        status    MB
0   bls_timeseries/bls_jt/jt-data-1-AllItems_2026-...  already have  34.5
1      bls_timeseries/bls_jt/jt-series_2026-10-12.txt  already have   0.2
2       bls_timeseries/bls_jt/jt-state_2026-10-12.txt  already have   0.0
3    bls_timeseries/bls_jt/jt-industry_2026-10-12.txt  already have   0.0
4   bls_timeseries/bls_jt/jt-dataelement_2026-10-1...  already have   0.0
5   bls_timeseries/bls_jt/jt-ratelevel_2026-10-12.txt  already have   0.0
6   bls_timeseries/bls_jt/jt-sizeclass_2026-10-12.txt  already have   0.0
7        bls_timeseries/bls_jt/jt-area_2026-10-12.txt  already have   0.0
8      bls_timeseries/bls_jt/jt-period_2026-10-12.txt  already have   0.0
9    bls_timeseries/bls_jt/jt-footnote_2026-10-12.txt  already have   0.0
10        bls_timeseries/bls_jt/jt-txt_2026-10-12.txt  already have   0.0
11  bls_timeseries/bls_la/la-data-39-NewYork_2026-...  already have  21.9
12     bls_timeseries/bls_la/la-series_2026-10-12.txt  already have   4.1
13       bls_timeseries/bls_la/la-area_2026-10-12.txt  already have   0.4
14    bls_timeseries/bls_la/la-measure_2026-10-12.txt  already have   0.0
15     bls_timeseries/bls_la/la-period_2026-10-12.txt  already have   0.0
16   bls_timeseries/bls_la/la-footnote_2026-10-12.txt  already have   0.0
17        bls_timeseries/bls_la/la-txt_2026-10-12.txt  already have   0.0
18  bls_timeseries/bls_cu/cu-data-1-AllItems_2026-...  already have   2.7
19     bls_timeseries/bls_cu/cu-series_2026-10-12.txt  already have   1.3
20       bls_timeseries/bls_cu/cu-area_2026-10-12.txt  already have   0.0
21       bls_timeseries/bls_cu/cu-item_2026-10-12.txt  already have   0.0
22     bls_timeseries/bls_cu/cu-period_2026-10-12.txt  already have   0.0
23   bls_timeseries/bls_cu/cu-footnote_2026-10-12.txt  already have   0.0
24        bls_timeseries/bls_cu/cu-txt_2026-10-12.txt  already have   0.0

## Summary
Anything not `downloaded` or `already have` needs a look. A failed file is not retried silently; it shows up here.

In [13]:
summary = pd.concat(log, names=["group"]).reset_index(level=0)
print(summary["status"].value_counts().to_string())
problems = summary[~summary["status"].isin(["downloaded", "already have"])]
problems

status
already have    146
downloaded        9

Empty DataFrame
Columns: [group, file, status, MB]
Index: []

In [14]:
manifest = pd.read_csv(S.MANIFEST)
print(f"manifest: {len(manifest)} files, {manifest['bytes'].sum()/1e9:.2f} GB")
manifest.groupby("group")["bytes"].agg(files="count", GB=lambda b: round(b.sum()/1e9, 2))

manifest: 155 files, 2.76 GB

                files    GB
group
bls_timeseries     25  0.07
graduates          27  0.11
hiring              5  0.29
jobs               26  1.35
licensing          39  0.00
outcomes           10  0.17
pay                13  0.64
postings            6  0.10
skills              4  0.03